# .github/workflows/main.yml

# Name of the Workflow
name: BestPrice CI/CD Pipeline

# trigger : when to run - on each push or pr
on:
  push:
    branches: [ main ] 
  # run on each PR
  pull_request:
    


# jobs: what to run
jobs:
  test-backend:
    runs-on: ubuntu-latest # just saying it linux

    steps:
     # first step: get the code
      - name: Checkout code
        uses: actions/checkout@v3

      # second step : install and setup python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13' 

      # third:  install dependencies
      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      # run the tests script
      - name: Run Backend Tests
        run: |
          chmod +x scripts/run_tests.sh
          bash scripts/run_tests.sh
      
      # get the html report
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: htmlcov/
          if-no-files-found: error

  # second job : test the frontend
  test-frontend:
    runs-on: ubuntu-latest

    steps:
      # get code
      - name: Checkout code
        uses: actions/checkout@v3

      # install node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # install the dependencies with npm
      - name: Install Frontend Dependencies
        run: npm install --prefix frontend

      # try to build the project to see it works
      - name: Build Frontend
        run: npm run build --prefix frontend

  build-and-push-docker:
    # Run only on push to main, after tests pass
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [test-backend, test-frontend] # Run only if tests passed
    runs-on: ubuntu-latest

    # Give this job permissions to write packages
    permissions:
      contents: read
      packages: write 

    
    steps:
      # get the code
      - name: Checkout code
        uses: actions/checkout@v3

        # login to git
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # This is your username (omrinahum)
          password: ${{ secrets.GITHUB_TOKEN }} # This is a temporary token provided by Actions

      - name: Build and push Docker image
        run: |
          # Build the image using the Dockerfile 
          docker build -t ghcr.io/omrinahum/bestprice:latest .
          
          # Push the image to GitHub Container Registry
          docker push ghcr.io/omrinahum/bestprice:latest

  # trigger render deployment hook to get the immage
  trigger-render-deploy:
    # Run only after the image is successfully built and pushed
    needs: [build-and-push-docker]
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK }}"